### ISSUE TITLE
MDX support

### ISSUE THREAD

**Issue by azat-io** [ilyatitovich/remark-lint-smarty-pants-typography#2]
In MDX, you can import components and use them inside Markdown.

You should refrain from changing single quotes to curly quotes when importing a component.

Example:

```mdx
import Blockquote from '~/components/Blockquote.astro'

# The hard way

<Blockquote author="Ernest Hemingway">
  The world breaks everyone and afterward many are strong at the broken places.
</Blockquote>
```

**Comment by ilyatitovich** [comment]
This plugin was developed specifically for the project and has some restrictions. It's just for linting regular .md docs. If MDX support is needed, check [remark-smartyypants](https://github.com/silvenon/remark-smartypants)
